weekly snapshot/backup

diff --git a/rogue b/rogue
--- a/rogue
+++ b/rogue
@@ -6,9 +6,11 @@ projects_dir="$HOME/Desktop/projects/"
 project_name="<Placeholder>"
 default_visiblity="private"  # Default to private
 commit_msg="Initial commit"
+default_msg="This is a default description message generated by RoguePM and will be changed in the future"
 license="mit"
 templates_dir="$HOME/Desktop/projects/RoguePM/RogueTemplates/" # must change it to somthing like bin as this will be a executable
 template="default"
+include_license="false"
 config_file="$HOME/.roguerc"
 
 
@@ -21,11 +23,38 @@ cat << "EOF"
                |___/             |_____|              
 EOF
 
+backup_projects(){
+	for dir in $projects_dir*; do
+		if [ -d "$dir/.git" ]; then
+			echo -e "\e[1m[Rogue]\e[0m Checking for changes in $dir"
+			cd "$dir" || continue
+			if ! git diff --quiet || ! git diff --cached --quiet; then
+				git add -A
+				git commit -m "weekly snapshot/backup"
+				branch=$(git symbolic-ref --short HEAD)
+				if [ "$branch" = "master" ] || [ "$branch" = "main" ]; then
+					echo -e "\e[1m[Rogue]\e[0m Pushing to Github remote in branch $branch"
+					git push origin "$branch"
+				else
+					echo -e "\e[1m[Rogue]\e[0m Skipping push: $dir is on branch $branch"
+				fi
+			else
+				echo -e "\e[1m[Rogue]\e[0m No changes is $dir, skipping..... "
+			fi
+		fi
+	done
+	return 1
+}
+
 # Parse arguments
 while [[ $# -gt 0 ]]; do
 	case "$1" in
 		new)read -p $'\e[1m[Rogue]\e[0m Enter project name: ' project_name
 			shift 
+			;;
+			
+		backup)
+			backup_projects
 			;;
 			
 		-r) replace="true"; shift ;;
@@ -62,8 +91,17 @@ while [[ $# -gt 0 ]]; do
 			fi
 			commit_msg="$2"; 
 			shift 2 ;;
+
+		-d) if [[ -z "$2" ]];then
+				echo -e "\e[1m[Rogue]\e[0m Error: Description message cannot be empty."
+				echo -e "\e[1m[Rogue]\e[0m Exiting......"
+				return 1
+			fi
+			default_msg="$2"; 
+			shift 2 ;;
 			
-		-l) if [[ -z "$2" ]];then
+		-l) include_license='true'
+			if [[ -z "$2" ]];then
 				echo -e "\e[1m[Rogue]\e[0m Error: License not specified."
 				echo -e "\e[1m[Rogue]\e[0m Using MIT license....."
 				license="mit"
@@ -113,10 +151,11 @@ GITHUB_USER=$(gh api user --jq .login)
 echo -e "\e[1m[Rogue]\e[0m GitHub username: $GITHUB_USER"
 echo -e "\e[1m[Rogue]\e[0m GitHub repository name: $project_name"
 echo -e "\e[1m[Rogue]\e[0m GitHub repository visibility: $default_visiblity"
+echo -e "\e[1m[Rogue]\e[0m GitHub repository description: $default_message"
 
 # Initialize Git
 git init
-gh repo create "$project_name" --"$default_visiblity" --source=. --remote=origin
+gh repo create "$project_name" --"$default_visiblity" --source=. --remote=origin --description "$default_msg"
 echo -e "\e[1m[Rogue]\e[0m GitHub repository created: https://github.com/$GITHUB_USER/$project_name"
 
 echo -e "\n[~~~~~~~~~~~~~~~|Creating Basic files and folders|~~~~~~~~~~~~~]"
@@ -132,3 +171,8 @@ git commit -m "$commit_msg"
 echo -e "\n[~~~~~~~~~~~~~~~~~~~~|Pushing to \e[1mMaster\e[0m branch|~~~~~~~~~~~~~~~~~~]"
 git push -u origin master
 echo -e "\n\e[1m[Rogue]\e[0m Exiting......"
+
+
+echo -e "\n[~~~~~~~~~~~~~~~~~~~~|Function to backup projects|~~~~~~~~~~~~~~~~~~]"
+
+
